### ISSUE TITLE
Not Supported icon

### ISSUE THREAD

**Issue by JDHatman** [salopensource/grahamgilbert-plugins#3]
Is there an option anywhere in the settings to enable a third category for the following encryption fact?
mac_encryption => Not supported

The numbers are a little off because it only shows encrypted/non-encrypted systems that are running 10.8 or newer.  It'd be nice if there was a third category that showed all the rest that are not compatible.

**Comment by grahamgilbert** [comment]
I'm going to close this. I'm not running anything less than 10.10, and I'd be amazed if people have many machines that are less than 10.8 and are concerned about encryption.
